eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9002
  
web: 
  ui-path: /Users/moc/idealinfo/works/ideal/ideal-parent/static
spring:
  application:
    name: bussiness-cloud
  datasource:
    username: crm_ms
    password: '@qwer1234'
    url: jdbc:mysql://192.168.2.180:3306/db_crm_ms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  resources:
    static-locations: classpath:/META-INF/resources/,
                      classpath:/resources/,
                      classpath:/static/,
                      classpath:/public/,
                      classpath:/itstyle/,
                      file:${web.ui-path}

feign: 
  hystrix: 
    enabled: true

mapper:
  mappers:
    - com.ideal.cloud.system.config.MapperGenerator
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

