eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #注册中心不需要注册自己
    register-with-eureka: false
    #注册中心不需要去发现服务
    fetch-registry: false
  server:
    #自我保护机制
    enable-self-preservation: true
spring:
  application:
    name: eurekaRegister
management:
  server:
    servlet:
      context-path: /
server:
  port: 8761